/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import controller.controller;
import domain.Hand;
import java.awt.Color;
import java.util.Random;
import javax.swing.ImageIcon;


/**
 *
 * @author mateo
 */
public class ui extends javax.swing.JFrame {
            
    /**
     * Creates new form ui
     */
    public ui() {
        initComponents();
        labelRockOne1.setVisible(false);
        labelRockTwo.setVisible(false);
        labelPaperOne.setVisible(false);
        labelPaperTwo.setVisible(false);
        labelScissorOne.setVisible(false);
        labelScissorTwo.setVisible(false);
        jLabelChooseOption.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelScreen = new javax.swing.JPanel();
        jLabelChooseOption = new javax.swing.JLabel();
        btnChooseTwoPlayer = new javax.swing.JButton();
        btnChooseOnePlayer1 = new javax.swing.JButton();
        labelRockTwo = new javax.swing.JLabel();
        labelScissorTwo = new javax.swing.JLabel();
        labelPaperTwo = new javax.swing.JLabel();
        labelPaperOne = new javax.swing.JLabel();
        labelScissorOne = new javax.swing.JLabel();
        jLabelTitle2 = new javax.swing.JLabel();
        jLabelResult = new javax.swing.JLabel();
        labelRockOne1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelChooseOption.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabelChooseOption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelChooseOption.setText("ELIJE UNA OPCION");
        jPanelScreen.add(jLabelChooseOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 410, 50));

        btnChooseTwoPlayer.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnChooseTwoPlayer.setText("2 JUGADORES");
        btnChooseTwoPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseTwoPlayerActionPerformed(evt);
            }
        });
        jPanelScreen.add(btnChooseTwoPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 310, 240, -1));

        btnChooseOnePlayer1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnChooseOnePlayer1.setText("1 JUGADOR");
        btnChooseOnePlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseOnePlayer1ActionPerformed(evt);
            }
        });
        jPanelScreen.add(btnChooseOnePlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 180, -1));

        labelRockTwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRockTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rock_icon_1.png"))); // NOI18N
        labelRockTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRockTwoMouseClicked(evt);
            }
        });
        jPanelScreen.add(labelRockTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 390, 150, 150));

        labelScissorTwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelScissorTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scissor_icon_3.png"))); // NOI18N
        jPanelScreen.add(labelScissorTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 550, 150, 150));

        labelPaperTwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPaperTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paper_icon_2.png"))); // NOI18N
        jPanelScreen.add(labelPaperTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 550, 150, 150));

        labelPaperOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPaperOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paper_icon_2.png"))); // NOI18N
        labelPaperOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPaperOneMouseClicked(evt);
            }
        });
        jPanelScreen.add(labelPaperOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, 150, 150));

        labelScissorOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelScissorOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scissor_icon_3.png"))); // NOI18N
        labelScissorOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelScissorOneMouseClicked(evt);
            }
        });
        jPanelScreen.add(labelScissorOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 150, 150));

        jLabelTitle2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabelTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle2.setText("PIEDRA, PAPEL, TIJERA!");
        jLabelTitle2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTitle2MouseClicked(evt);
            }
        });
        jPanelScreen.add(jLabelTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 410, 50));

        jLabelResult.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabelResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelScreen.add(jLabelResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 540, 90));

        labelRockOne1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRockOne1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rock_icon_1.png"))); // NOI18N
        labelRockOne1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRockOne1MouseClicked(evt);
            }
        });
        jPanelScreen.add(labelRockOne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 150, 150));

        getContentPane().add(jPanelScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseTwoPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseTwoPlayerActionPerformed
        // TODO add your handling code here:
        labelRockOne1.setVisible(true);
        labelPaperOne.setVisible(true);
        labelScissorOne.setVisible(true);
        btnChooseTwoPlayer.hide();
        btnChooseOnePlayer1.hide();
        labelRockTwo.setVisible(true);
        labelPaperTwo.setVisible(true);
        labelScissorTwo.setVisible(true);
        twoPlayers = true;
        
        //Usamos el objeto controlador para la primera eleccion del usuario

    }//GEN-LAST:event_btnChooseTwoPlayerActionPerformed

    private void btnChooseOnePlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseOnePlayer1ActionPerformed
        // TODO add your handling code here:
        btnChooseTwoPlayer.hide();
        btnChooseOnePlayer1.hide();
        jLabelChooseOption.setVisible(true);
        labelRockOne1.setVisible(true);
        labelPaperOne.setVisible(true);
        labelScissorOne.setVisible(true);
        onePlayer = true;
    }//GEN-LAST:event_btnChooseOnePlayer1ActionPerformed

    private void labelPaperOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPaperOneMouseClicked
        // TODO add your handling code here:
        controladorOpcionUsuario.setHand(Hand.PAPEL);
        //System.out.println("La decision del usuario ha sido"+ controladorOpcionUsuario.getHand().getIndex());
                /*
        Se ejecutar un ciclo if para verificar si la varibale onePlayer es true es decir si solo esta jugando una persona
        */
         if(onePlayer== true){
             //Definiremos un rango en el cual se ejecutara el modulo random 
             Integer min_value = 0;
             Integer max_value = 3;
             Random ran = new Random();
             comoputerChoice = ran.nextInt(max_value) + min_value;
             System.out.println(comoputerChoice); //Se imprime por consola el numero random generado
             if(comoputerChoice == 0){
                 controller controladorComputadora = new controller();
                 controladorComputadora.setHand(Hand.PIEDRA);
                 jLabelResult.setText("GANASTE, CONTINUA ASI!!");
                 jPanelScreen.setBackground(Color.green);
                 System.out.println("Tu eleccion fue:"+ controladorOpcionUsuario.getHand()+ "Eleccion del PC:" + controladorComputadora.getHand());
             }else if(comoputerChoice == 1){
                 System.out.println("ELIGIO PAPEL LA PC");
                 controller controladorComputadora = new controller();
                 controladorComputadora.setHand(Hand.PAPEL);
                 jLabelResult.setText("EMPATE!!");
                 jPanelScreen.setBackground(Color.yellow);
                 System.out.println("Tu eleccion fue:"+ controladorOpcionUsuario.getHand()+ "Eleccion del PC:" + controladorComputadora.getHand());
             }else if(comoputerChoice == 2){
                 System.out.println("ELIGIO TIJERA LA PC");
                 controller controladorComputadora = new controller();
                 controladorComputadora.setHand(Hand.TIJERA);
                 jLabelResult.setText("PERDISTE, INTENTA NUEVAMENTE!!");
                 jPanelScreen.setBackground(Color.red);
                 System.out.println("Tu eleccion fue:"+ controladorOpcionUsuario.getHand()+ "Eleccion del PC:" + controladorComputadora.getHand());
             }
         }else if(twoPlayers == true){
             System.out.println("LOGICA PARA DOS JUGADORES");
             //ToDo: Logica para dos jugadores
         }
    }//GEN-LAST:event_labelPaperOneMouseClicked

    private void labelScissorOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelScissorOneMouseClicked
        // TODO add your handling code here:
        controladorOpcionUsuario.setHand(Hand.TIJERA);
        //System.out.println("La decision del usuario ha sido"+ controladorOpcionUsuario.getHand().getIndex());
                 if(onePlayer== true){
             //Definiremos un rango en el cual se ejecutara el modulo random 
             Integer min_value = 0;
             Integer max_value = 3;
             Random ran = new Random();
             comoputerChoice = ran.nextInt(max_value) + min_value;
             System.out.println(comoputerChoice);
             if(comoputerChoice == 0){
                 controller controladorComputadora = new controller();
                 controladorComputadora.setHand(Hand.PIEDRA);
                 jLabelResult.setText("PERDISTE, INTENTA NUEVAMENTEI!!");
                 jPanelScreen.setBackground(Color.red);
                 System.out.println("Tu eleccion fue:"+ controladorOpcionUsuario.getHand()+ "Eleccion del PC:" + controladorComputadora.getHand());
             }else if(comoputerChoice == 1){
                 System.out.println("ELIGIO PAPEL LA PC");
                 controller controladorComputadora = new controller();
                 controladorComputadora.setHand(Hand.PAPEL);
                 jLabelResult.setText("GANASTEE!!");
                 jPanelScreen.setBackground(Color.green);
                 System.out.println("Tu eleccion fue:"+ controladorOpcionUsuario.getHand()+ "Eleccion del PC:" + controladorComputadora.getHand());
             }else if(comoputerChoice == 2){
                 System.out.println("ELIGIO TIJERA LA PC");
                 controller controladorComputadora = new controller();
                 controladorComputadora.setHand(Hand.TIJERA);
                 jLabelResult.setText("EMPATE, SIGUE INTENTANDO!!");
                 jPanelScreen.setBackground(Color.yellow);
                 System.out.println("Tu eleccion fue:"+ controladorOpcionUsuario.getHand()+ "Eleccion del PC:" + controladorComputadora.getHand());
             }
         }
    }//GEN-LAST:event_labelScissorOneMouseClicked

    private void jLabelTitle2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTitle2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelTitle2MouseClicked

    private void labelRockOne1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRockOne1MouseClicked
        // TODO add your handling code here:
        controladorOpcionUsuario.setHand(Hand.PIEDRA);
         //System.out.println("La decision del usuario ha sido"+ controladorOpcionUsuario.getHand().getIndex());
         if(onePlayer== true){
             //Definiremos un rango en el cual se ejecutara el modulo random 
             Integer min_value = 0;
             Integer max_value = 3;
             Random ran = new Random();
             comoputerChoice = ran.nextInt(max_value) + min_value;
             System.out.println(comoputerChoice);
             if(comoputerChoice == 0){
                 controller controladorComputadora = new controller();
                 controladorComputadora.setHand(Hand.PIEDRA);
                 jLabelResult.setText("EMPATEI!!");
                 jPanelScreen.setBackground(Color.yellow);
                 System.out.println("Tu eleccion fue:"+ controladorOpcionUsuario.getHand()+ "Eleccion del PC:" + controladorComputadora.getHand());
             }else if(comoputerChoice == 1){
                 //System.out.println("ELIGIO PAPEL LA PC");
                 controller controladorComputadora = new controller();
                 controladorComputadora.setHand(Hand.PAPEL);
                 jLabelResult.setText("PERDISTE, SIGUE INTENTANDO!!");
                 jPanelScreen.setBackground(Color.red);
                 System.out.println("Tu eleccion fue:"+ controladorOpcionUsuario.getHand()+ "Eleccion del PC:" + controladorComputadora.getHand());
             }else if(comoputerChoice == 2){
                 //System.out.println("ELIGIO TIJERA LA PC");
                 controller controladorComputadora = new controller();
                 controladorComputadora.setHand(Hand.TIJERA);
                 jLabelResult.setText("GANASTE, CONTINUA ASI!!");
                 jPanelScreen.setBackground(Color.green);
                 System.out.println("Tu eleccion fue:"+ controladorOpcionUsuario.getHand()+ "Eleccion del PC:" + controladorComputadora.getHand());
             }
         }  
    }//GEN-LAST:event_labelRockOne1MouseClicked

    private void labelRockTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRockTwoMouseClicked
        // TODO add your handling code here:
        controladorOpcionSegundoUsuario.setHand(Hand.PIEDRA);
        System.out.println(controladorOpcionSegundoUsuario.getHand());
        if (controladorOpcionUsuario.getHand() == null){
            
        }
    }//GEN-LAST:event_labelRockTwoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ui().setVisible(true);
            }
        });
    }
    public void addIndex(Integer index){
        controller choiceOne = new controller();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseOnePlayer1;
    private javax.swing.JButton btnChooseTwoPlayer;
    private javax.swing.JLabel jLabelChooseOption;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JLabel jLabelTitle2;
    private javax.swing.JPanel jPanelScreen;
    private javax.swing.JLabel labelPaperOne;
    private javax.swing.JLabel labelPaperTwo;
    private javax.swing.JLabel labelRockOne1;
    private javax.swing.JLabel labelRockTwo;
    private javax.swing.JLabel labelScissorOne;
    private javax.swing.JLabel labelScissorTwo;
    // End of variables declaration//GEN-END:variables
    controller controladorOpcionUsuario = new controller(); 
    public boolean onePlayer = false;
    public Integer comoputerChoice;
    controller controladorOpcionSegundoUsuario = new controller();
    int x,y;
    //ImageIcon rock = new ImageIcon("imagenes/rock_icon_1.png");
    public boolean twoPlayers = false;

}
